item {
  id: 1
  name: 'group_of_people'
}
item {
  id: 2
  name: 'pedestrian'
}
item {
  id: 3
  name: 'person'
}
item {
  id: 4
  name: 'bicycle'
}
item {
  id: 5
  name: 'car'
}
item {
  id: 6
  name: 'van'
}
item {
  id: 7
  name: 'truck'
}
item {
  id: 8
  name: 'awning tricycle'
}
item {
  id: 9
  name: 'tricycle'
}
item {
  id: 10
  name: 'bus'
}
item {
  id: 11
  name: 'motorbike'
}
item {
  id: 12
  name: 'bike'
}
